const Shop = require('../schema/shop-schema'); // Assuming you're exporting the Mongoose model

const createItem = async (req, res) => {
    const { itemPic, itemPrice, itemName , category } = req.body;

    // Proper validation logic (comma-separated conditions won't work)
    if (!itemPic || !itemPrice || !itemName || !category) {
        return res.status(400).json({ message: "All fields are required" });
    }

    try {
        const newItem = new Shop({
            itemPic,
            itemPrice,
            itemName,
            category,
            // itemCode will be auto-generated by pre-save middleware
        });

        const savedItem = await newItem.save();
        res.status(201).json(savedItem);
    } catch (error) {
        console.error("Error creating item:", error);
        res.status(500).json({ message: "Server error while creating item" });
    }
};

module.exports = createItem;
